name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    paths:
        - "**.php"
        - ".github/workflows/*.yml"
        - "!docs/**"

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code
    services:
      mariadb:
        image: mariadb:10
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        # Ensure docker waits for mariadb to start
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
          coverage: none
          tools: composer:v2, wp-cli

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-progress"

      - name: Setup WordPress
        run: |
          cp .env.dist .env
          composer run install-test-env
          cp -R . /tmp/wordpress/wp-content/plugins/wp-gatsby

      - name: Run PHPStan
        working-directory: /tmp/wordpress/wp-content/plugins/wp-gatsby
        run: composer run-script phpstan
