name: WordPress Coding Standards

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    paths:
        - "**.php"
        - ".github/workflows/*.yml"
        - "!docs/**"

jobs:
  run:
    runs-on: ubuntu-latest
    name: Checkout repo
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-progress"

      - name: Run PHP_CodeSniffer
        run: composer run-script lint
