name: Create Source Plugin PR
on:
  pull_request:
    types: [opened]
    branches:
      - develop
      - master
jobs:
  create_pr:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          curl --request POST \
            --url https://api.github.com/repos/gatsbyjs/gatsby-source-wordpress-experimental/actions/workflows/wp-gatsby-pr.yml/dispatches \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "ref": "master",
            "inputs": { "remoteref": $GITHUB_REF }
          }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
