name: Automated-Testing

on:
  schedule:
    - cron:  '0 4 * * 5'
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '**.php'
      - '!docs/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '7.3'
        wordpress:
          - '5.6'
          - '5.5.3'
          - '5.4.2'
      fail-fast: false
    name: WordPress ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-dev

      - name: Build "testing" Docker Image
        env:
          PHP_VERSION: ${{ matrix.php }}
          WP_VERSION: ${{ matrix.wordpress }}
        run: composer build-test

      - name: Run Tests w/ Docker.
        run: composer run-test
